---

# Playbook to deploy a Dockerized ELK stack

- name: Deploy Elk Server
  hosts: servers
  become: yes
  become_user: root
  remote_user: root
  roles:
    - users
    - docker
    - elk-docker
  tags: 
    - elk

- name: Deploy Filebeat
  hosts: elk-server
  become: yes
  become_user: root
  remote_user: root
  roles:
    - filebeat
  tags:
    - filebeat

- name: Deploy MySQL Server
  hosts: mysql-server
  become: yes
  become_user: root
  remote_user: root
  roles:
    - mysql-docker
  tags:
    - mysql

- name: Deploy Redis Server
  hosts: redis-server
  become: yes
  become_user: root
  remote_user: root
  roles:
    - docker-redis
  tags:
    - redis

- name: Deploy PHP Server
  hosts: php-server
#  become: yes
#  become_user: root
  remote_user: root
  roles:
    - php-docker
  tags:
    - php

- name: Deploy MySQL, PHP, Ngnix Containers
  hosts: servers
  remote_user: root
  roles:
    - mysqlphpngnix-docker
  tags:
    - fullstack

