---

- name: Create MySQL Dataload directory
  file:
    path: "/etc/mysql/dataload"
    state: directory
    mode: 0777

- name: Copy MySQL dataload file
  template:
    src: "dump.sql.j2"
    dest: "/etc/mysql/dataload/dump.sql"
    mode: 0766

- name: Create MySQL Data directory
  file:
    path: "/etc/mysql/data"
    state: directory
    mode: 0777

